# Generated by Django 6.0.1 on 2026-03-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='problem_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
