# Generated by Django 6.0.1 on 2026-02-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20260217_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_pic_url',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/customers/'),
        ),
        migrations.AddField(
            model_name='servicemanprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/servicemen/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/vendors/'),
        ),
    ]
