# Generated by Django 6.0.1 on 2026-03-12 09:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_booking_problem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='job_lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='job_location_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='job_long',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_labor_cost',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_material_cost',
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_date',
            field=models.DateField(default=datetime.date(2026, 3, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='scheduled_time',
            field=models.TimeField(default=datetime.time(9, 17, 27, 340034)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='service_charge_at_booking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.customerprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='problem_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='serviceman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.servicemanprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
