# Generated by Django 6.0.1 on 2026-03-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_booking_grand_total_remove_booking_job_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
