# Generated by Django 6.0.1 on 2026-03-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_service_latitude_service_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicemanprofile',
            old_name='hourly_charges',
            new_name='visiting_charge',
        ),
    ]
