# Generated by Django 6.0.1 on 2026-02-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_opening_hours_vendorprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
