# Generated by Django 6.0.1 on 2026-02-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_servicemanprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
