# Generated by Django 6.0.1 on 2026-02-25 11:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_servicemanprofile_is_active_vendorprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemanprofile',
            name='kyc_docs_url',
        ),
        migrations.AddField(
            model_name='servicemanprofile',
            name='hourly_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicemanprofile',
            name='kyc_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='servicemanprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
