# Generated by Django 5.2.11 on 2026-03-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='bookingitem',
            name='home_bookin_booking_81e8e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='home_produc_vendor__75daeb_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='home_produc_categor_cb7dec_idx',
        ),
        migrations.RemoveIndex(
            model_name='service',
            name='home_servic_service_3e27ea_idx',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='base_price',
        ),
        migrations.AlterUniqueTogether(
            name='bookingitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceman',
        ),
        migrations.AddField(
            model_name='service',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_alert',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
