# Generated by Django 6.0.1 on 2026-03-02 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_servicemanprofile_kyc_docs_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanoffering',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
