# Generated by Django 5.2.11 on 2026-03-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_booking_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
