# Generated by Django 5.2.11 on 2026-03-25 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_bookingitem_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitem',
            old_name='price_at_booking',
            new_name='product_price',
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='product_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='product_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='product_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
    ]
