# Generated by Django 5.2.11 on 2026-03-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_price_at_booking_bookingitem_product_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitem',
            name='product',
        ),
    ]
