# Generated by Django 5.2.11 on 2026-03-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_bookingitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
    ]
