# Generated by Django 5.2.11 on 2026-03-27 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_bookingitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='customer_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_orders', to='home.booking'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='serviceman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_orders', to='home.servicemanprofile'),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_orders', to='home.vendorprofile'),
        ),
    ]
