# Generated by Django 5.2.11 on 2026-03-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_materialorder_customer_approve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING_PAYMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(blank=True, choices=[('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_signature', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.booking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customerprofile')),
            ],
        ),
    ]
