# Generated by Django 5.2.11 on 2026-03-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_booking_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
