# Generated by Django 5.2.11 on 2026-04-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_bookingitem_is_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialorder',
            name='urgency',
        ),
    ]
