# Generated by Django 5.2.11 on 2026-04-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_materialorder_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialorder',
            name='is_collected',
            field=models.BooleanField(default=False),
        ),
    ]
