# Generated by Django 5.2.11 on 2026-04-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_materialorder_is_collected'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_vendor_distance_km', models.IntegerField(default=10)),
            ],
        ),
    ]
