# Generated by Django 5.2.11 on 2026-04-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_appsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSettings',
        ),
    ]
