# Generated by Django 5.2.11 on 2026-04-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_appsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('VENDOR_ACCEPTED', 'Vendor Accepted'), ('DELIVERED', 'Delivered'), ('AUTO_REJECTED', 'Auto Rejected'), ('FULFILLED', 'Fulfilled')], default='REQUESTED', max_length=20),
        ),
    ]
