# Generated by Django 5.2.11 on 2026-04-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_materialorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(default='Visiting', max_length=100),
        ),
    ]
