# Generated by Django 5.0.4 on 2026-04-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(default='Visiting', max_length=50),
        ),
    ]
