# Generated by Django 5.2.11 on 2026-04-09 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_materialorderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='vendor',
        ),
    ]
