# Generated by Django 5.2.11 on 2026-04-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_orderitem_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='service_charge_at_booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='visiting_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='assigned_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='home.vendorprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('STRIPE', 'Stripe')], default='RAZORPAY', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('VISITING', 'Visiting'), ('VISITING_SERVICE', 'Visiting + Service')], default='VISITING', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
