# Generated by Django 5.0.4 on 2026-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_payment_payment_type_alter_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(blank=True, to='home.service'),
        ),
        migrations.AddField(
            model_name='materialorder',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materialorder',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('VENDOR_ACCEPTED', 'Vendor Accepted'), ('COLLECTED', 'Collected by Serviceman'), ('DELIVERED', 'Delivered'), ('AUTO_REJECTED', 'Auto Rejected'), ('FULFILLED', 'Fulfilled')], default='REQUESTED', max_length=20),
        ),
    ]
