# Generated by Django 5.2.11 on 2026-04-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_booking_services_materialorder_tracking_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingitem',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('AUTO_REJECTED', 'Auto Rejected')], default='PENDING', max_length=20),
        ),
    ]
