# Generated by Django 5.0.4 on 2026-05-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
