# Generated by Django 6.0.4 on 2026-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_servicemanprofile_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visiting_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
