# Generated by Django 6.0.4 on 2026-05-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_category_visiting_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=20.0, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
