# Generated by Django 6.0.4 on 2026-05-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemanprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
