# Generated by Django 6.0.4 on 2026-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_servicemanprofile_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='admin_payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
