# Generated by Django 6.0.4 on 2026-05-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_withdrawalrequest_admin_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='upi_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
