# Generated by Django 6.0.4 on 2026-05-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_withdrawalrequest_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
