# Generated by Django 6.0.4 on 2026-05-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_category_is_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='trending_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
