# Generated by Django 6.0.4 on 2026-05-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_category_trending_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='visiting_charge',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
