# Generated by Django 6.0.4 on 2026-05-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_category_visiting_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select a parent category if this is a subcategory.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.category'),
        ),
    ]
